create table public.report_queue (
  id bigint generated by default as identity not null,
  emp_id character varying not null,
  user_name text not null,
  report_id text not null,
  title text not null,
  status text not null,
  start_date date not null,
  end_date date not null,
  created_at timestamp without time zone null default now(),
  constraint report_queue_pkey primary key (id),
  constraint report_queue_emp_id_fkey foreign KEY (emp_id) references user_access_master (emp_id)
) TABLESPACE pg_default;
