-- 1. Create the Master Log Table
-- This table will store all historical changes (Transitional Data)
-- Now enhanced with specific user metadata, transaction IDs, and change diffs.
CREATE TABLE public.system_transitional_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,           -- Name of the table being modified
    record_id TEXT,                     -- ID of the record
    operation_type TEXT NOT NULL,       -- 'INSERT', 'UPDATE', 'DELETE'
    
    -- Snapshot Data
    old_record JSONB,                   -- Previous state
    new_record JSONB,                   -- New state
    changes_diff JSONB,                 -- Computed JSON diff (only changed fields)
    
    -- Metadata
    changed_by TEXT,                    -- Auth User ID (UUID)
    user_email TEXT,                    -- Snapshot of email at time of change
    user_role TEXT,                     -- Snapshot of role at time of change
    
    transaction_id BIGINT DEFAULT txid_current(), -- Groups atomic operations together
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    client_info JSONB                   -- IP, User Agent (if provided via app context)
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.system_transitional_log ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow read access to Admins only
CREATE POLICY "Admins can view audit logs"
ON public.system_transitional_log
FOR SELECT
USING (
  auth.uid() IN (
    SELECT id FROM auth.users 
    WHERE raw_user_meta_data->>'role' = 'Admin'
  )
);

-- ==========================================
-- AUTOMATION VIA TRIGGERS
-- ==========================================

-- 4. Enhanced Trigger Function
CREATE OR REPLACE FUNCTION log_any_change()
RETURNS TRIGGER AS $$
DECLARE
    v_old_data JSONB;
    v_new_data JSONB;
    v_diff JSONB;
    v_user_id TEXT;
    v_email TEXT;
    v_role TEXT;
BEGIN
    -- Prepare JSON snapshots
    IF (TG_OP = 'UPDATE') THEN
        v_old_data := to_jsonb(OLD);
        v_new_data := to_jsonb(NEW);
        
        -- Compute simple top-level key difference
        -- (Selects keys from NEW that are different from OLD)
        SELECT jsonb_object_agg(key, value)
        INTO v_diff
        FROM jsonb_each(v_new_data)
        WHERE NOT (v_old_data ? key) OR (v_old_data -> key) <> value;
        
    ELSIF (TG_OP = 'DELETE') THEN
        v_old_data := to_jsonb(OLD);
        v_new_data := NULL;
        v_diff := v_old_data; -- For delete, "diff" is the lost record (or null, depending on pref)
    ELSIF (TG_OP = 'INSERT') THEN
        v_old_data := NULL;
        v_new_data := to_jsonb(NEW);
        v_diff := v_new_data; -- For insert, diff is the new record
    END IF;

    -- Extract User Info safely
    v_user_id := auth.uid()::text;
    v_email := current_setting('request.jwt.claims', true)::jsonb ->> 'email';
    v_role := current_setting('request.jwt.claims', true)::jsonb ->> 'role';

    -- Insert Log
    INSERT INTO public.system_transitional_log (
        table_name,
        record_id,
        operation_type,
        old_record,
        new_record,
        changes_diff,
        changed_by,
        user_email,
        user_role,
        changed_at
    )
    VALUES (
        TG_TABLE_NAME,
        -- Robust ID extraction (tries 'id', then 'user_id', then 'uuid')
        COALESCE(
            (CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END)::jsonb->>'id',
            (CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END)::jsonb->>'user_id',
            (CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END)::jsonb->>'uuid',
            'unknown'
        ),
        TG_OP,
        v_old_data,
        v_new_data,
        v_diff,
        v_user_id,
        v_email,
        v_role,
        NOW()
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Example Usage (Uncomment to apply)
-- CREATE TRIGGER audit_distributor_master
-- AFTER INSERT OR UPDATE OR DELETE ON "Distributor_Master"
-- FOR EACH ROW EXECUTE FUNCTION log_any_change();

-- CREATE TRIGGER audit_users
-- AFTER INSERT OR UPDATE OR DELETE ON public.user_access_master
-- FOR EACH ROW EXECUTE FUNCTION log_any_change();
