create table public."Distributor_Master" (
  "DB ID" bigint not null,
  "Status" text null,
  "RSM" text null,
  "RSM ID" bigint null,
  "ASM" text null,
  "ASM ID" bigint null,
  "EXECUTIVE" text null,
  "REGION" text null,
  "DISTRICT" text null,
  "PLANT" text null,
  "TEHSIL" text null,
  "DB Name" text null,
  "NAME OF DISTRIBUTOR" text null,
  "ADDRESS" text null,
  "PIN CODE" bigint null,
  "Lat" text null,
  "Long" text null,
  "DB CONTACT NO. 1" bigint null,
  "DB CONTACT NO. 2" text null,
  "Email" text null,
  "ADHAR" text null,
  "PAN NO." text null,
  "DOB" text null,
  "GST" text null,
  "DOJ" text null,
  "Exclusive / 
Non-
Exclusive" text null,
  "Welcome Kit" text null,
  "Plant Visit" text null,
  "Open Remark" text null,
  "Close Remark" text null,
  constraint Distributor_Master_pkey primary key ("DB ID")
) TABLESPACE pg_default;
