-- Create the Territory History table
create table public.territory_history (
  id bigint generated by default as identity primary key,
  db_id bigint not null references public."Distributor_Master" ("DB ID"),
  asm_id bigint not null references public.user_access_master (user_id),
  asm_name text not null,
  assigned_by text null,
  start_date timestamp with time zone default now(),
  end_date timestamp with time zone null,
  reason text null
) tablespace pg_default;

-- Add an index for faster lookups by distributor
create index if not exists idx_territory_history_db_id on public.territory_history (db_id);
